version: '3.8'

services:
  app:
    image: algoduck-app
    container_name: algoduck
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9404:9404" # JMX Exporter
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${EC2_DB_HOST}:3306/${DB_NAME}?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_PROFILE_BUCKET_NAME: ${S3_PROFILE_BUCKET_NAME}
      S3_TESTCASE_BUCKET_NAME: ${S3_TESTCASE_BUCKET_NAME}
      DEFAULT_PROFILE_URL: ${DEFAULT_PROFILE_URL}

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  grafana-storage:
