spring.application.name=algoduck
spring.datasource.url=jdbc:mysql://localhost:3306/algoduck_local_dev?serverTimezone=Asia/Seoul
spring.datasource.username=algoduck_local_dev
spring.datasource.password=algoduck_local_dev