name: Deploy Algoduck to EC2

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate application.yml
        run: |
          mkdir -p src/main/resources
          cat <<EOF > src/main/resources/application.yml
          spring:
            application:
              name: algoduck

            datasource:
              url: ${{ secrets.DATASOURCE_URL }}
              username: ${{ secrets.DB_USER_NAME }}
              password: ${{ secrets.DB_PASSWORD }}
            jpa:
              hibernate:
                ddl-auto: create
              show-sql: false
              properties:
                hibernate.format_sql: true
                hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

            servlet:
              multipart:
                enabled: true
                max-file-size: 10MB
                max-request-size: 10MB

            cloud:
              aws:
                credentials:
                  access-key: ${{ secrets.AWS_ACCESS_KEY }}
                  secret-key: ${{ secrets.AWS_SECRET_KEY }}
                region:
                  static: ap-northeast-2
                s3:
                  profile_bucket: ${{ secrets.S3_PROFILE_BUCKET_NAME }}

          logging:
            level:
              org.hibernate.SQL: DEBUG
              org.hibernate.type.descriptor.sql.BasicBinder: TRACE

          app:
            default:
              profile-image-url: ${{ secrets.DEFAULT_PROFILE_URL }}

          springdoc:
            api-docs:
              path: /api-docs
            swagger-ui:
              path: /swagger-ui.html
              operationsSorter: alpha
              defaultModelsExpandDepth: -1
          EOF

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Copy JAR and Dockerfile to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar,Dockerfile"
          target: "~/algoduck"

      - name: SSH into EC2 and run Docker commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/algoduck
            docker stop algoduck || true && docker rm algoduck || true
            docker rmi algoduck-app || true
            docker build -t algoduck-app .
            docker run -d -p 8080:8080 --name algoduck algoduck-app

